services:
  moontv-core:
    image: ghcr.io/mtvpls/moontvplus:latest
    container_name: moontv-core
    restart: on-failure
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./robots.txt:/app/public/robots.txt
    environment:
      - USERNAME=admin
      - PASSWORD=Aa661119.
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks:6666
      - SITE_BASE=https://www.godshan.cloud
    networks:
      - moontv-network
    depends_on:
      - moontv-kvrocks

  moontv-kvrocks:
    image: apache/kvrocks
    container_name: moontv-kvrocks
    restart: unless-stopped
    volumes:
      - /opt/data/moontv/kvrocks-data:/var/lib/kvrocks/data
    networks:
      - moontv-network

networks:
  moontv-network:
    driver: bridge
