services:
  moontv-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moontv-core
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - PASSWORD=${PASSWORD:?PASSWORD is required}
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks:6666
    depends_on:
      - moontv-kvrocks
    networks:
      - moontv-network

  moontv-kvrocks:
    image: apache/kvrocks
    container_name: moontv-kvrocks
    restart: unless-stopped
    volumes:
      - kvrocks-data:/var/lib/kvrocks/data
    networks:
      - moontv-network

networks:
  moontv-network:
    driver: bridge

volumes:
  kvrocks-data:
