services:
  moontv-core:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moontv-core
    restart: on-failure
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./robots.txt:/app/public/robots.txt
    environment:
      - USERNAME=${MOONTV_USERNAME:?MOONTV_USERNAME is required}
      - PASSWORD=${MOONTV_PASSWORD:?MOONTV_PASSWORD is required}
      - NEXT_PUBLIC_STORAGE_TYPE=kvrocks
      - KVROCKS_URL=redis://moontv-kvrocks:6666
      - SITE_BASE=https://www.godshan.cloud
    networks:
      - moontv-network
    depends_on:
      - moontv-kvrocks

  moontv-kvrocks:
    image: apache/kvrocks
    container_name: moontv-kvrocks
    restart: unless-stopped
    volumes:
      - kvrocks-data:/var/lib/kvrocks/data
    networks:
      - moontv-network

networks:
  moontv-network:
    driver: bridge

volumes:
  kvrocks-data:
